services:
  web-socket:
    build: ./web-socket
    ports:
      - "8081:8080"

  blog-fetcher:
    build: ./blog-fetcher
    ports:
      - "8082:8080"

  frontend:
    build: ./frontend
    ports:
      - "80:80"