services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web-socket:
    build: ./web-socket
    ports:
      - "8081:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  blog-fetcher:
    build: ./blog-fetcher
    ports:
      - "8082:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./frontend
    ports:
      - "80:80"
